#!/usr/bin/env python3
"""
verify_analytic.py — Numerical sanity check for the analytic lemmas in
notes/analytic-reference.md.

Checks two closed-form predictions against the committed WP-C datasets:

  Lemma A (motional heterodyne). At δ=0 and T_gap = T_m, U_gap = 𝟙 on
  the motional block. Verified by comparing the numerically-built gap
  diagonal against the identity across the Fock cutoff.

  Lemma B (impulsive V floor). V_imp = (1 + exp(-2η²))/2. Verified by
  comparing the analytic value at η = 0.397 against:
    (i) the numerical impulsive-limit overlay generated by
        compute_impulsive_V in plot_coastline.py.
    (ii) the explicit per-ϑ₀ expression
        |C|(ϑ₀) = ½ √(1 - 2·exp(-2η²)·cos(4η|α|·cos ϑ₀) + exp(-4η²))
        min_{ϑ₀} |C| ≈ ½ (1 - exp(-2η²))   for |α| ≥ π/(4η).

Prints the verdict; nonzero exit on failure.
"""
from __future__ import annotations

import os
import sys
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..', 'scripts')))
sys.path.insert(0, SCRIPT_DIR)  # for plot_coastline.compute_impulsive_V

from stroboscopic import propagators as prop

ETA = 0.397
OMEGA_M = 1.3
T_M = 2 * np.pi / OMEGA_M


def check_lemma_A() -> tuple[bool, float]:
    """Gap diagonal at δ=0, t_gap = T_m → all entries should equal 1."""
    gap = prop.build_U_gap(
        nmax=80, omega_m=OMEGA_M, t_gap=T_M, delta=0.0,
        include_motion=True, include_spin_detuning=True,
    )
    deviation = float(np.max(np.abs(np.asarray(gap) - 1.0)))
    ok = deviation < 1e-10
    return ok, deviation


def analytic_V_imp(eta: float) -> float:
    return 0.5 * (1.0 + np.exp(-2.0 * eta ** 2))


def analytic_coh_formula(eta: float, alpha: float, theta0_grid):
    """|C|(ϑ₀) = ½√(1 - 2e^(-2η²) cos(4η|α| cos ϑ₀) + e^(-4η²))."""
    dw1 = np.exp(-2.0 * eta ** 2)
    dw2 = np.exp(-4.0 * eta ** 2)
    arg = 4.0 * eta * alpha * np.cos(theta0_grid)
    return 0.5 * np.sqrt(1.0 - 2.0 * dw1 * np.cos(arg) + dw2)


def check_lemma_B_analytic_formula() -> tuple[bool, float, float]:
    """Closed-form min_ϑ |C| vs the expected ½(1 − e^{−2η²}) floor."""
    theta0 = np.linspace(0.0, 2 * np.pi, 2048, endpoint=False)
    V_vals = []
    # Sweep |α| across the full v0.1 scan range (|α| ≥ π/(4η) ≈ 1.98
    # guarantees the cosine argument spans a full period).
    alphas = np.array([0.0, 1.0, 2.0, 3.0, 5.0, 8.0])
    for a in alphas:
        coh = analytic_coh_formula(ETA, a, theta0)
        V_vals.append(1.0 - coh.min())
    V_vals = np.array(V_vals)
    V_floor = analytic_V_imp(ETA)
    # For |α| ≥ π/(4η) ≈ 1.98, V should saturate the floor.
    saturated = V_vals[alphas >= 2.0]
    max_dev = float(np.max(np.abs(saturated - V_floor)))
    ok = max_dev < 1e-10
    return ok, max_dev, V_floor


def check_lemma_B_numerical_match() -> tuple[bool, float, float]:
    """Analytic V_imp vs the numerical impulsive-limit overlay."""
    from plot_coastline import compute_impulsive_V  # noqa: E402
    N_list = np.array([3, 6, 12, 24, 48, 96])
    V_num = compute_impulsive_V(alpha=3.0, N_list=N_list,
                                omega_m=OMEGA_M, n_theta0=64)
    V_analytic = analytic_V_imp(ETA)
    max_dev = float(np.max(np.abs(V_num - V_analytic)))
    # 64-point θ₀ grid may not resolve the floor to machine precision;
    # accept up to 1e-3 deviation.
    ok = max_dev < 1e-3
    return ok, max_dev, V_analytic


def main():
    print(f"verify_analytic — η={ETA}, ω_m={OMEGA_M} (angular)\n")
    any_fail = False

    print("Lemma A (motional heterodyne at t_gap = T_m, δ = 0):")
    okA, devA = check_lemma_A()
    print(f"  U_gap deviation from identity: {devA:.3e}  "
          f"[{'PASS' if okA else 'FAIL'}]\n")
    any_fail |= not okA

    print("Lemma B closed-form (|α| ≥ π/(4η) saturation):")
    okB1, devB1, floor = check_lemma_B_analytic_formula()
    print(f"  V_floor = ½(1 + e^(-2η²)) = {floor:.6f}")
    print(f"  max |V_analytic(|α|≥2) − V_floor| = {devB1:.3e}  "
          f"[{'PASS' if okB1 else 'FAIL'}]\n")
    any_fail |= not okB1

    print("Lemma B vs numerical impulsive-limit overlay (|α| = 3, "
          "N ∈ {3,6,12,24,48,96}):")
    okB2, devB2, Va = check_lemma_B_numerical_match()
    print(f"  V_analytic = {Va:.6f}")
    print(f"  max |V_numerical(N) − V_analytic| = {devB2:.3e}  "
          f"[{'PASS' if okB2 else 'FAIL'}]\n")
    any_fail |= not okB2

    if any_fail:
        print("VERDICT: one or more analytic checks failed.")
        sys.exit(1)
    print("VERDICT: all analytic lemmas match numerics within tolerance.")


if __name__ == '__main__':
    main()
